import type {
  Ticket,
  Agent,
  Department,
  Client,
  KbArticle,
  Contract,
  AuditLogEntry,
  NotificationItem,
} from "./types";

export const departments: Department[] = [
  { id: "dep-1", name: "Payments & Settlements", lead: "Ngozi Adeyemi", agents: 8, openTickets: 34, slaCompliance: 93 },
  { id: "dep-2", name: "Card Services", lead: "Tunde Bakare", agents: 6, openTickets: 21, slaCompliance: 88 },
  { id: "dep-3", name: "Onboarding & KYC", lead: "Fatima Sule", agents: 5, openTickets: 17, slaCompliance: 96 },
  { id: "dep-4", name: "Technical Integration", lead: "David Okonkwo", agents: 7, openTickets: 29, slaCompliance: 81 },
  { id: "dep-5", name: "Billing & Disputes", lead: "Amaka Chukwu", agents: 4, openTickets: 12, slaCompliance: 91 },
];

export const agents: Agent[] = [
  { id: "agt-1", name: "Ngozi Adeyemi", initials: "NA", department: "Payments & Settlements", role: "Team Lead", activeTickets: 6, resolvedThisMonth: 58, csat: 4.7, slaCompliance: 95 },
  { id: "agt-2", name: "Tunde Bakare", initials: "TB", department: "Card Services", role: "Team Lead", activeTickets: 5, resolvedThisMonth: 44, csat: 4.5, slaCompliance: 89 },
  { id: "agt-3", name: "Chiamaka Nwosu", initials: "CN", department: "Payments & Settlements", role: "Agent", activeTickets: 9, resolvedThisMonth: 71, csat: 4.8, slaCompliance: 97 },
  { id: "agt-4", name: "Emeka Okafor", initials: "EO", department: "Technical Integration", role: "Agent", activeTickets: 11, resolvedThisMonth: 39, csat: 4.2, slaCompliance: 78 },
  { id: "agt-5", name: "Blessing Eze", initials: "BE", department: "Onboarding & KYC", role: "Agent", activeTickets: 7, resolvedThisMonth: 52, csat: 4.9, slaCompliance: 98 },
  { id: "agt-6", name: "Segun Adio", initials: "SA", department: "Billing & Disputes", role: "Agent", activeTickets: 4, resolvedThisMonth: 33, csat: 4.4, slaCompliance: 92 },
  { id: "agt-7", name: "Fatima Sule", initials: "FS", department: "Onboarding & KYC", role: "Team Lead", activeTickets: 3, resolvedThisMonth: 28, csat: 4.6, slaCompliance: 94 },
  { id: "agt-8", name: "David Okonkwo", initials: "DO", department: "Technical Integration", role: "Team Lead", activeTickets: 8, resolvedThisMonth: 47, csat: 4.3, slaCompliance: 82 },
];

export const clients: Client[] = [
  { id: "cli-1", company: "Helder Bespoke", contact: "Ezekiel Johnson", email: "ezekiel@helderbespoke.com", tier: "Priority" },
  { id: "cli-2", company: "QuikFi Technologies", contact: "Amara Obi", email: "amara@quikfi.com", tier: "Enterprise" },
  { id: "cli-3", company: "Lagos Retail Co.", contact: "Ibrahim Musa", email: "ibrahim@lagosretail.com", tier: "Standard" },
  { id: "cli-4", company: "Verdant Foods Ltd.", contact: "Chidinma Eze", email: "chidinma@verdantfoods.com", tier: "Priority" },
];

export const tickets: Ticket[] = [
  {
    id: "TCK-10482",
    subject: "Settlement batch failed for 07 Jul disbursement",
    description:
      "Yesterday's settlement batch for merchant payouts did not post to our nominated account. Reference file attached shows a mismatch between the expected and reconciled amount of ₦4.2M.",
    client: "QuikFi Technologies",
    contact: "Amara Obi",
    department: "Payments & Settlements",
    category: "Settlement Failure",
    status: "Escalated",
    priority: "Critical",
    assignedTo: "Chiamaka Nwosu",
    createdAt: "2026-07-06T08:12:00Z",
    updatedAt: "2026-07-07T07:40:00Z",
    dueAt: "2026-07-07T12:12:00Z",
    tatHoursTotal: 4,
    tatHoursElapsed: 3.5,
    slaState: "At Risk",
    csat: null,
    escalationLevel: 2,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-06T08:12:00Z" },
      { id: "e2", type: "assignment", actor: "Ngozi Adeyemi", message: "Assigned to Chiamaka Nwosu.", timestamp: "2026-07-06T08:20:00Z" },
      { id: "e3", type: "comment", actor: "Chiamaka Nwosu", message: "Pulling the reconciliation file from the settlement engine now.", timestamp: "2026-07-06T09:05:00Z", internal: true },
      { id: "e4", type: "escalation", actor: "System", message: "Auto-escalated to Level 2: TAT threshold at 80% reached.", timestamp: "2026-07-07T07:00:00Z" },
      { id: "e5", type: "comment", actor: "Chiamaka Nwosu", message: "Confirmed a rounding mismatch in batch #88213. Fix is being deployed by the payments engineering team, ETA 2 hours.", timestamp: "2026-07-07T07:40:00Z" },
    ],
  },
  {
    id: "TCK-10479",
    subject: "Unable to generate virtual card for new sub-account",
    description: "When creating a virtual card for our new sub-merchant account, the API returns a 500 error at the card issuance step.",
    client: "Helder Bespoke",
    contact: "Ezekiel Johnson",
    department: "Card Services",
    category: "Card Issuance",
    status: "In Progress",
    priority: "High",
    assignedTo: "Tunde Bakare",
    createdAt: "2026-07-05T14:02:00Z",
    updatedAt: "2026-07-06T16:20:00Z",
    dueAt: "2026-07-07T14:02:00Z",
    tatHoursTotal: 24,
    tatHoursElapsed: 17.5,
    slaState: "On Track",
    csat: null,
    escalationLevel: 0,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-05T14:02:00Z" },
      { id: "e2", type: "assignment", actor: "Tunde Bakare", message: "Self-assigned.", timestamp: "2026-07-05T14:30:00Z" },
      { id: "e3", type: "comment", actor: "Tunde Bakare", message: "Reproduced the issue in staging. Looks like a KYC-tier restriction on the sub-account. Checking with compliance.", timestamp: "2026-07-06T16:20:00Z" },
    ],
  },
  {
    id: "TCK-10475",
    subject: "Dispute: duplicate charge on invoice INV-2291",
    description: "We were billed twice for our June subscription. Requesting a refund for the duplicate transaction.",
    client: "Lagos Retail Co.",
    contact: "Ibrahim Musa",
    department: "Billing & Disputes",
    category: "Billing Dispute",
    status: "Resolved",
    priority: "Medium",
    assignedTo: "Segun Adio",
    createdAt: "2026-07-03T09:15:00Z",
    updatedAt: "2026-07-04T11:00:00Z",
    dueAt: "2026-07-06T09:15:00Z",
    tatHoursTotal: 72,
    tatHoursElapsed: 25.75,
    slaState: "Met",
    csat: 5,
    escalationLevel: 0,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-03T09:15:00Z" },
      { id: "e2", type: "assignment", actor: "Segun Adio", message: "Assigned to Segun Adio.", timestamp: "2026-07-03T09:40:00Z" },
      { id: "e3", type: "comment", actor: "Segun Adio", message: "Confirmed duplicate charge from a webhook retry. Refund of ₦48,000 processed to source account.", timestamp: "2026-07-04T10:50:00Z" },
      { id: "e4", type: "status", actor: "Segun Adio", message: "Marked as Resolved.", timestamp: "2026-07-04T11:00:00Z" },
      { id: "e5", type: "comment", actor: "Ibrahim Musa", message: "Confirmed refund received, thank you for the quick turnaround.", timestamp: "2026-07-04T13:10:00Z" },
    ],
  },
  {
    id: "TCK-10471",
    subject: "Webhook signature verification failing intermittently",
    description: "About 1 in 20 webhook deliveries fail signature verification on our end despite using the documented HMAC method.",
    client: "QuikFi Technologies",
    contact: "Amara Obi",
    department: "Technical Integration",
    category: "API Integration",
    status: "Open",
    priority: "High",
    assignedTo: "Emeka Okafor",
    createdAt: "2026-07-04T10:30:00Z",
    updatedAt: "2026-07-06T09:00:00Z",
    dueAt: "2026-07-06T10:30:00Z",
    tatHoursTotal: 48,
    tatHoursElapsed: 47,
    slaState: "Breached",
    csat: null,
    escalationLevel: 1,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-04T10:30:00Z" },
      { id: "e2", type: "assignment", actor: "David Okonkwo", message: "Assigned to Emeka Okafor.", timestamp: "2026-07-04T11:00:00Z" },
      { id: "e3", type: "sla", actor: "System", message: "SLA breached at 48h TAT threshold.", timestamp: "2026-07-06T10:30:00Z" },
      { id: "e4", type: "comment", actor: "Emeka Okafor", message: "Root cause identified: payload re-encoding differs on retried deliveries. Patch in review.", timestamp: "2026-07-06T09:00:00Z" },
    ],
  },
  {
    id: "TCK-10468",
    subject: "KYC document re-verification for tier upgrade",
    description: "Requesting an upgrade from Standard to Enterprise tier, submitting updated CAC documents for re-verification.",
    client: "Verdant Foods Ltd.",
    contact: "Chidinma Eze",
    department: "Onboarding & KYC",
    category: "Account Upgrade",
    status: "New",
    priority: "Low",
    assignedTo: null,
    createdAt: "2026-07-07T06:05:00Z",
    updatedAt: "2026-07-07T06:05:00Z",
    dueAt: "2026-07-10T06:05:00Z",
    tatHoursTotal: 72,
    tatHoursElapsed: 1.5,
    slaState: "On Track",
    csat: null,
    escalationLevel: 0,
    events: [{ id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-07T06:05:00Z" }],
  },
  {
    id: "TCK-10460",
    subject: "Chargeback notification not reflecting in dashboard",
    description: "A chargeback was raised against transaction TXN-88213 but it isn't showing in our disputes dashboard.",
    client: "Lagos Retail Co.",
    contact: "Ibrahim Musa",
    department: "Billing & Disputes",
    category: "Reporting Issue",
    status: "On Hold",
    priority: "Medium",
    assignedTo: "Segun Adio",
    createdAt: "2026-07-02T12:00:00Z",
    updatedAt: "2026-07-05T15:00:00Z",
    dueAt: "2026-07-09T12:00:00Z",
    tatHoursTotal: 168,
    tatHoursElapsed: 116,
    slaState: "On Track",
    csat: null,
    escalationLevel: 0,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-02T12:00:00Z" },
      { id: "e2", type: "comment", actor: "Segun Adio", message: "Waiting on the acquiring bank to confirm chargeback reference. Placed on hold pending their response.", timestamp: "2026-07-05T15:00:00Z" },
    ],
  },
  {
    id: "TCK-10455",
    subject: "Bulk payout CSV template request",
    description: "Could we get the latest bulk payout CSV template? The one we have seems outdated for the new schema.",
    client: "Helder Bespoke",
    contact: "Ezekiel Johnson",
    department: "Payments & Settlements",
    category: "General Inquiry",
    status: "Closed",
    priority: "Low",
    assignedTo: "Ngozi Adeyemi",
    createdAt: "2026-06-29T09:00:00Z",
    updatedAt: "2026-06-29T13:20:00Z",
    dueAt: "2026-07-01T09:00:00Z",
    tatHoursTotal: 48,
    tatHoursElapsed: 4.3,
    slaState: "Met",
    csat: 4,
    escalationLevel: 0,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-06-29T09:00:00Z" },
      { id: "e2", type: "comment", actor: "Ngozi Adeyemi", message: "Attached the current v3 bulk payout template and a migration note for the new schema.", timestamp: "2026-06-29T13:00:00Z" },
      { id: "e3", type: "status", actor: "Ngozi Adeyemi", message: "Marked as Closed.", timestamp: "2026-06-29T13:20:00Z" },
    ],
  },
  {
    id: "TCK-10450",
    subject: "POS terminal not dispensing receipts after firmware update",
    description: "Following the 2.3.1 firmware push, terminals in 3 branches stopped printing receipts though transactions succeed.",
    client: "Verdant Foods Ltd.",
    contact: "Chidinma Eze",
    department: "Technical Integration",
    category: "Hardware",
    status: "Escalated",
    priority: "Critical",
    assignedTo: "David Okonkwo",
    createdAt: "2026-07-06T18:45:00Z",
    updatedAt: "2026-07-07T08:10:00Z",
    dueAt: "2026-07-06T22:45:00Z",
    tatHoursTotal: 4,
    tatHoursElapsed: 13.4,
    slaState: "Breached",
    csat: null,
    escalationLevel: 3,
    events: [
      { id: "e1", type: "status", actor: "System", message: "Ticket created from client portal.", timestamp: "2026-07-06T18:45:00Z" },
      { id: "e2", type: "assignment", actor: "System", message: "Auto-assigned to David Okonkwo (Critical priority).", timestamp: "2026-07-06T18:46:00Z" },
      { id: "e3", type: "sla", actor: "System", message: "SLA breached at 4h TAT threshold.", timestamp: "2026-07-06T22:45:00Z" },
      { id: "e4", type: "escalation", actor: "System", message: "Escalated to Level 3: Management notified.", timestamp: "2026-07-07T02:00:00Z" },
      { id: "e5", type: "comment", actor: "David Okonkwo", message: "Firmware rollback scheduled for all affected terminals at 09:00 WAT.", timestamp: "2026-07-07T08:10:00Z" },
    ],
  },
];

export const kbArticles: KbArticle[] = [
  { id: "kb-1", title: "Understanding settlement batch cut-off times", category: "Payments & Settlements", summary: "How disbursement batches are scheduled, cut-off windows, and what to do if a batch appears delayed.", views: 3402, helpfulPct: 92, updatedAt: "2026-06-18" },
  { id: "kb-2", title: "Issuing your first virtual card via API", category: "Card Services", summary: "Step-by-step guide to card issuance, required KYC tier, and common 4xx/5xx error codes.", views: 2871, helpfulPct: 88, updatedAt: "2026-06-02" },
  { id: "kb-3", title: "Verifying webhook signatures (HMAC-SHA256)", category: "Technical Integration", summary: "Correctly compute and verify the X-Signature header to avoid intermittent verification failures.", views: 5190, helpfulPct: 95, updatedAt: "2026-06-25" },
  { id: "kb-4", title: "KYC document requirements by account tier", category: "Onboarding & KYC", summary: "Documents required for Standard, Priority, and Enterprise tiers, and average review timelines.", views: 4023, helpfulPct: 90, updatedAt: "2026-05-30" },
  { id: "kb-5", title: "Raising and tracking a billing dispute", category: "Billing & Disputes", summary: "How to submit a dispute, evidence required, and expected resolution timelines.", views: 1988, helpfulPct: 86, updatedAt: "2026-06-10" },
  { id: "kb-6", title: "Reading your SLA and TAT indicators", category: "General", summary: "What On Track, At Risk, and Breached mean, and how TAT is calculated per priority tier.", views: 2650, helpfulPct: 94, updatedAt: "2026-06-29" },
];

export const contracts: Contract[] = [
  { id: "ctr-1", client: "QuikFi Technologies", plan: "Enterprise", startDate: "2025-09-01", endDate: "2026-08-31", ticketAllowance: 500, ticketsUsed: 312, responseTimeHrs: 1, resolutionTimeHrs: 8, status: "Active" },
  { id: "ctr-2", client: "Helder Bespoke", plan: "Priority", startDate: "2025-11-15", endDate: "2026-08-15", ticketAllowance: 200, ticketsUsed: 168, responseTimeHrs: 2, resolutionTimeHrs: 24, status: "Expiring Soon" },
  { id: "ctr-3", client: "Lagos Retail Co.", plan: "Standard", startDate: "2026-01-01", endDate: "2026-12-31", ticketAllowance: 100, ticketsUsed: 41, responseTimeHrs: 4, resolutionTimeHrs: 72, status: "Active" },
  { id: "ctr-4", client: "Verdant Foods Ltd.", plan: "Priority", startDate: "2025-06-01", endDate: "2026-06-01", ticketAllowance: 200, ticketsUsed: 199, responseTimeHrs: 2, resolutionTimeHrs: 24, status: "Expired" },
];

export const auditLog: AuditLogEntry[] = [
  { id: "aud-1", user: "System", action: "SLA Breach", entity: "TCK-10450", oldValue: "On Track", newValue: "Breached", timestamp: "2026-07-06T22:45:00Z", ip: "10.0.4.12" },
  { id: "aud-2", user: "David Okonkwo", action: "Escalation", entity: "TCK-10450", oldValue: "Level 2", newValue: "Level 3", timestamp: "2026-07-07T02:00:00Z", ip: "197.210.44.18" },
  { id: "aud-3", user: "Chiamaka Nwosu", action: "Comment Added", entity: "TCK-10482", oldValue: "-", newValue: "Internal note added", timestamp: "2026-07-07T07:40:00Z", ip: "197.210.55.90" },
  { id: "aud-4", user: "Ngozi Adeyemi", action: "Assignment", entity: "TCK-10482", oldValue: "Unassigned", newValue: "Chiamaka Nwosu", timestamp: "2026-07-06T08:20:00Z", ip: "197.210.44.02" },
  { id: "aud-5", user: "Segun Adio", action: "Status Update", entity: "TCK-10475", oldValue: "In Progress", newValue: "Resolved", timestamp: "2026-07-04T11:00:00Z", ip: "197.210.61.71" },
  { id: "aud-6", user: "Admin: Bisi Fashola", action: "Configuration Change", entity: "SLA Policy: Critical", oldValue: "6 hours", newValue: "4 hours", timestamp: "2026-07-01T09:12:00Z", ip: "197.210.10.44" },
  { id: "aud-7", user: "Ezekiel Johnson", action: "Login", entity: "Client Portal", oldValue: "-", newValue: "Session started", timestamp: "2026-07-07T07:58:00Z", ip: "105.112.8.204" },
  { id: "aud-8", user: "Amara Obi", action: "Ticket Created", entity: "TCK-10482", oldValue: "-", newValue: "Settlement batch failed for 07 Jul disbursement", timestamp: "2026-07-06T08:12:00Z", ip: "105.113.20.61" },
  { id: "aud-9", user: "Tunde Bakare", action: "SLA Extension", entity: "TCK-10460", oldValue: "2026-07-08T12:00:00Z", newValue: "2026-07-09T12:00:00Z", timestamp: "2026-07-05T15:05:00Z", ip: "197.210.44.51" },
  { id: "aud-10", user: "Admin: Bisi Fashola", action: "User Deactivated", entity: "Agent: Kunle Ade", oldValue: "Active", newValue: "Deactivated", timestamp: "2026-06-30T16:40:00Z", ip: "197.210.10.44" },
  { id: "aud-11", user: "Segun Adio", action: "Logout", entity: "Staff Portal", oldValue: "Session active", newValue: "Session ended", timestamp: "2026-07-04T17:02:00Z", ip: "197.210.61.71" },
];

export const notifications: NotificationItem[] = [
  { id: "n1", title: "SLA at risk: TCK-10482", body: "Settlement batch failure ticket is 87% through its TAT window.", timestamp: "2026-07-07T07:40:00Z", read: false, type: "sla" },
  { id: "n2", title: "New reply on TCK-10479", body: "Tunde Bakare replied to your virtual card issuance ticket.", timestamp: "2026-07-06T16:20:00Z", read: false, type: "comment" },
  { id: "n3", title: "Ticket resolved: TCK-10475", body: "Your billing dispute has been resolved. Please share your feedback.", timestamp: "2026-07-04T11:00:00Z", read: true, type: "system" },
  { id: "n4", title: "Ticket assigned", body: "TCK-10482 was assigned to Chiamaka Nwosu.", timestamp: "2026-07-06T08:20:00Z", read: true, type: "assignment" },
];

export const ticketVolumeSeries = [
  { day: "Mon", created: 42, resolved: 38 },
  { day: "Tue", created: 51, resolved: 45 },
  { day: "Wed", created: 38, resolved: 40 },
  { day: "Thu", created: 60, resolved: 52 },
  { day: "Fri", created: 55, resolved: 58 },
  { day: "Sat", created: 21, resolved: 25 },
  { day: "Sun", created: 18, resolved: 20 },
];

export const slaComplianceTrend = [
  { month: "Feb", compliance: 89 },
  { month: "Mar", compliance: 91 },
  { month: "Apr", compliance: 87 },
  { month: "May", compliance: 93 },
  { month: "Jun", compliance: 90 },
  { month: "Jul", compliance: 92 },
];

export const departmentPerformance = departments.map((d) => ({
  name: d.name,
  compliance: d.slaCompliance,
  openTickets: d.openTickets,
}));

export const csatBreakdown = [
  { label: "5 - Excellent", value: 58, color: "#16A34A" },
  { label: "4 - Good", value: 26, color: "#4ade80" },
  { label: "3 - Average", value: 10, color: "#facc15" },
  { label: "2 - Poor", value: 4, color: "#f97316" },
  { label: "1 - Very Poor", value: 2, color: "#dc2626" },
];
